name: Test Homebrew Formula

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual execution

jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Homebrew
        run: brew update

      - name: Tap asimov-platform
        run: brew tap asimov-platform/tap https://github.com/asimov-platform/homebrew-tap.git

      - name: Install asimov-cli
        run: brew install asimov-platform/tap/asimov-cli

      - name: Verify Installation
        run: |
          which asimov-cli
          asimov-cli --version

  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install build-essential curl -y

      - name: Install Homebrew (Linux)
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ~/.bashrc
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

      - name: Tap asimov-platform
        run: brew tap asimov-platform/tap https://github.com/asimov-platform/homebrew-tap.git

      - name: Install asimov-cli
        run: brew install asimov-platform/tap/asimov-cli

      - name: Verify Installation
        run: |
          which asimov-cli
          asimov-cli --version
